# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'UI.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(844, 507)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.btn7 = QPushButton(self.centralwidget)
        self.btn7.setObjectName(u"btn7")
        self.btn7.setGeometry(QRect(730, 220, 101, 41))
        self.btn14 = QPushButton(self.centralwidget)
        self.btn14.setObjectName(u"btn14")
        self.btn14.setGeometry(QRect(730, 280, 101, 41))
        self.btn6 = QPushButton(self.centralwidget)
        self.btn6.setObjectName(u"btn6")
        self.btn6.setGeometry(QRect(620, 220, 101, 41))
        self.btn13 = QPushButton(self.centralwidget)
        self.btn13.setObjectName(u"btn13")
        self.btn13.setGeometry(QRect(620, 280, 101, 41))
        self.btn21 = QPushButton(self.centralwidget)
        self.btn21.setObjectName(u"btn21")
        self.btn21.setGeometry(QRect(730, 340, 101, 41))
        self.btn20 = QPushButton(self.centralwidget)
        self.btn20.setObjectName(u"btn20")
        self.btn20.setGeometry(QRect(620, 340, 101, 41))
        self.btn28 = QPushButton(self.centralwidget)
        self.btn28.setObjectName(u"btn28")
        self.btn28.setGeometry(QRect(730, 400, 101, 41))
        self.btn27 = QPushButton(self.centralwidget)
        self.btn27.setObjectName(u"btn27")
        self.btn27.setGeometry(QRect(620, 400, 101, 41))
        self.btn5 = QPushButton(self.centralwidget)
        self.btn5.setObjectName(u"btn5")
        self.btn5.setGeometry(QRect(500, 220, 101, 41))
        self.btn4 = QPushButton(self.centralwidget)
        self.btn4.setObjectName(u"btn4")
        self.btn4.setGeometry(QRect(380, 220, 101, 41))
        self.btn12 = QPushButton(self.centralwidget)
        self.btn12.setObjectName(u"btn12")
        self.btn12.setGeometry(QRect(500, 280, 101, 41))
        self.btn19 = QPushButton(self.centralwidget)
        self.btn19.setObjectName(u"btn19")
        self.btn19.setGeometry(QRect(500, 340, 101, 41))
        self.btn18 = QPushButton(self.centralwidget)
        self.btn18.setObjectName(u"btn18")
        self.btn18.setGeometry(QRect(380, 340, 101, 41))
        self.btn26 = QPushButton(self.centralwidget)
        self.btn26.setObjectName(u"btn26")
        self.btn26.setGeometry(QRect(500, 400, 101, 41))
        self.btn11 = QPushButton(self.centralwidget)
        self.btn11.setObjectName(u"btn11")
        self.btn11.setGeometry(QRect(380, 280, 101, 41))
        self.btn25 = QPushButton(self.centralwidget)
        self.btn25.setObjectName(u"btn25")
        self.btn25.setGeometry(QRect(380, 400, 101, 41))
        self.btn3 = QPushButton(self.centralwidget)
        self.btn3.setObjectName(u"btn3")
        self.btn3.setGeometry(QRect(260, 220, 101, 41))
        self.btn8 = QPushButton(self.centralwidget)
        self.btn8.setObjectName(u"btn8")
        self.btn8.setGeometry(QRect(20, 280, 101, 41))
        self.btn17 = QPushButton(self.centralwidget)
        self.btn17.setObjectName(u"btn17")
        self.btn17.setGeometry(QRect(260, 340, 101, 41))
        self.btn23 = QPushButton(self.centralwidget)
        self.btn23.setObjectName(u"btn23")
        self.btn23.setGeometry(QRect(140, 400, 101, 41))
        self.btn22 = QPushButton(self.centralwidget)
        self.btn22.setObjectName(u"btn22")
        self.btn22.setGeometry(QRect(20, 400, 101, 41))
        self.btn10 = QPushButton(self.centralwidget)
        self.btn10.setObjectName(u"btn10")
        self.btn10.setGeometry(QRect(260, 280, 101, 41))
        self.btn2 = QPushButton(self.centralwidget)
        self.btn2.setObjectName(u"btn2")
        self.btn2.setGeometry(QRect(140, 220, 101, 41))
        self.btn15 = QPushButton(self.centralwidget)
        self.btn15.setObjectName(u"btn15")
        self.btn15.setGeometry(QRect(20, 340, 101, 41))
        self.btn16 = QPushButton(self.centralwidget)
        self.btn16.setObjectName(u"btn16")
        self.btn16.setGeometry(QRect(140, 340, 101, 41))
        self.btn1 = QPushButton(self.centralwidget)
        self.btn1.setObjectName(u"btn1")
        self.btn1.setGeometry(QRect(20, 220, 101, 41))
        self.btn9 = QPushButton(self.centralwidget)
        self.btn9.setObjectName(u"btn9")
        self.btn9.setGeometry(QRect(140, 280, 101, 41))
        self.btn24 = QPushButton(self.centralwidget)
        self.btn24.setObjectName(u"btn24")
        self.btn24.setGeometry(QRect(260, 400, 101, 41))
        self.radio_btn1 = QRadioButton(self.centralwidget)
        self.radio_btn1.setObjectName(u"radio_btn1")
        self.radio_btn1.setGeometry(QRect(20, 90, 151, 21))
        self.label_1 = QLabel(self.centralwidget)
        self.label_1.setObjectName(u"label_1")
        self.label_1.setGeometry(QRect(460, 90, 251, 16))
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(460, 120, 271, 21))
        self.checkbox1 = QCheckBox(self.centralwidget)
        self.checkbox1.setObjectName(u"checkbox1")
        self.checkbox1.setGeometry(QRect(280, 90, 82, 21))
        self.checkbox2 = QCheckBox(self.centralwidget)
        self.checkbox2.setObjectName(u"checkbox2")
        self.checkbox2.setGeometry(QRect(280, 120, 82, 21))
        self.checkbox3 = QCheckBox(self.centralwidget)
        self.checkbox3.setObjectName(u"checkbox3")
        self.checkbox3.setGeometry(QRect(280, 150, 82, 21))
        self.language_selector_box = QComboBox(self.centralwidget)
        self.language_selector_box.setObjectName(u"language_selector_box")
        self.language_selector_box.setGeometry(QRect(668, 10, 161, 23))
        self.radio_btn2 = QRadioButton(self.centralwidget)
        self.radio_btn2.setObjectName(u"radio_btn2")
        self.radio_btn2.setGeometry(QRect(20, 120, 151, 21))
        self.radio_btn3 = QRadioButton(self.centralwidget)
        self.radio_btn3.setObjectName(u"radio_btn3")
        self.radio_btn3.setGeometry(QRect(20, 150, 151, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 844, 20))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Multi Language", None))
        self.btn7.setText(QCoreApplication.translate("MainWindow", u"Button 7", None))
        self.btn14.setText(QCoreApplication.translate("MainWindow", u"Button 14", None))
        self.btn6.setText(QCoreApplication.translate("MainWindow", u"Button 6", None))
        self.btn13.setText(QCoreApplication.translate("MainWindow", u"Button 13", None))
        self.btn21.setText(QCoreApplication.translate("MainWindow", u"Button 21", None))
        self.btn20.setText(QCoreApplication.translate("MainWindow", u"Button 20", None))
        self.btn28.setText(QCoreApplication.translate("MainWindow", u"Button 28", None))
        self.btn27.setText(QCoreApplication.translate("MainWindow", u"Button 27", None))
        self.btn5.setText(QCoreApplication.translate("MainWindow", u"Button 5", None))
        self.btn4.setText(QCoreApplication.translate("MainWindow", u"Button 4", None))
        self.btn12.setText(QCoreApplication.translate("MainWindow", u"Button 12", None))
        self.btn19.setText(QCoreApplication.translate("MainWindow", u"Button 19", None))
        self.btn18.setText(QCoreApplication.translate("MainWindow", u"Button 18", None))
        self.btn26.setText(QCoreApplication.translate("MainWindow", u"Button 26", None))
        self.btn11.setText(QCoreApplication.translate("MainWindow", u"Button 11", None))
        self.btn25.setText(QCoreApplication.translate("MainWindow", u"Button 25", None))
        self.btn3.setText(QCoreApplication.translate("MainWindow", u"Button 3", None))
        self.btn8.setText(QCoreApplication.translate("MainWindow", u"Button 8", None))
        self.btn17.setText(QCoreApplication.translate("MainWindow", u"Button 17", None))
        self.btn23.setText(QCoreApplication.translate("MainWindow", u"Button 23", None))
        self.btn22.setText(QCoreApplication.translate("MainWindow", u"Button 22", None))
        self.btn10.setText(QCoreApplication.translate("MainWindow", u"Button 10", None))
        self.btn2.setText(QCoreApplication.translate("MainWindow", u"Button 2", None))
        self.btn15.setText(QCoreApplication.translate("MainWindow", u"Button 15", None))
        self.btn16.setText(QCoreApplication.translate("MainWindow", u"Button 16", None))
        self.btn1.setText(QCoreApplication.translate("MainWindow", u"Button 1", None))
        self.btn9.setText(QCoreApplication.translate("MainWindow", u"Button 9", None))
        self.btn24.setText(QCoreApplication.translate("MainWindow", u"Button 24", None))
        self.radio_btn1.setText(QCoreApplication.translate("MainWindow", u"Option Button 1", None))
        self.label_1.setText(QCoreApplication.translate("MainWindow", u"Just Random text I put it here", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"This app is multi language support", None))
        self.checkbox1.setText(QCoreApplication.translate("MainWindow", u"Option 1", None))
        self.checkbox2.setText(QCoreApplication.translate("MainWindow", u"Option 2", None))
        self.checkbox3.setText(QCoreApplication.translate("MainWindow", u"Option 3", None))
        self.radio_btn2.setText(QCoreApplication.translate("MainWindow", u"Option Button 2", None))
        self.radio_btn3.setText(QCoreApplication.translate("MainWindow", u"Option Button 3", None))
    # retranslateUi

